#!/usr/bin/bash
title="$1"

name="$(echo $title | iconv  -t ASCII//TRANSLIT -f utf-8 | tr '[:upper:]' '[:lower:]' | tr ' ' '_')"
echo $name
date="$(date +%Y-%m-%d)"
filename="src/aktuality/$date-$name.md"
echo $filename

echo "---" > $filename
echo title: $title >> $filename
echo --- >> $filename

vim $filename
