name: Build web

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.3"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Install Lua dependencies
      run: |
        luarocks install h5tk 
        luarocks install date 

    - name: Download lettersmith
      uses: actions/checkout@v2
      with:
        repository:  michal-h21/lettersmith 
        path: lettersmith

    - name: Install lettersmith
      working-directory: lettersmith
      run: luarocks make

    - name: Download blog code
      uses: actions/checkout@v2
      with:
        repository:  michal-h21/pedf-web-navrh
        path: code

    - name: Build web
      working-directory: code
      run: | 
        echo $WWW_DIR
        lua web.lua
      env:
        HTML_DIR: ${{ env.GITHUB_WORKSPACE }}/src
        DATA_DIR: ${{ env.GITHUB_WORKSPACE }}/code/data
        WWW_DIR: ${{ env.GITHUB_WORKSPACE }}/www

    - name: Test if it works
      run: cat www/index.html



