name: Build web

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Cache lua installation
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: .lua
        key: ${{ runner.os }}-build-${{ env.cache-name }}-
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-


    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.3"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Cache luarocks modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: .luarocks
        key: ${{ runner.os }}-build-${{ env.cache-name }}-
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Lua dependencies
      run: |
        luarocks install h5tk 
        luarocks install date 

    - name: Download lettersmith
      uses: actions/checkout@v2
      with:
        repository:  michal-h21/lettersmith 
        path: lettersmith

    - name: Install lettersmith
      working-directory: lettersmith
      run: luarocks make

    - name: Download blog code
      uses: actions/checkout@v2
      with:
        repository:  michal-h21/pedf-web-navrh
        path: code

    - name: Build web
      working-directory: code
      run: | 
        export HTML_DIR=$GITHUB_WORKSPACE/src
        export DATA_DIR=$GITHUB_WORKSPACE/code/data
        export WWW_DIR=$GITHUB_WORKSPACE/www
        echo $WWW_DIR
        lua web.lua
        cp js/*.* $WWW_DIR/js/

    - name: Test if it works
      run: cat www/js/calendar.js

    - name: Deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USER }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "www"
        dist_target_dir: "www"
        only_newer: "true"
        ignore_time: "true"

    # - name: Deploy
    #   shell: bash
    #   run: |
    #     sudo apt-get install lftp
    #     mkdir ~/.lftp
    #     echo set ssl:verify-certificate false > ~/.lftp/rc
    #     echo host:  $FTP_HOST
    #     lftp -c "open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; mirror -c -p -R -L www www; exit;"
    #   env:
    #     $FTP_HOST: ${{ secrets.FTP_HOST }}
    #     $FTP_USER: ${{ secrets.FTP_USER }}
    #     $FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}






