name: Build web

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.3"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: .luarocks
        key: ${{ runner.os }}-build-${{ env.cache-name }}-
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Lua dependencies
      run: |
        luarocks install h5tk 
        luarocks install date 

    - name: Download lettersmith
      uses: actions/checkout@v2
      with:
        repository:  michal-h21/lettersmith 
        path: lettersmith

    - name: Install lettersmith
      working-directory: lettersmith
      run: luarocks make

    - name: Download blog code
      uses: actions/checkout@v2
      with:
        repository:  michal-h21/pedf-web-navrh
        path: code

    - name: Build web
      working-directory: code
      run: | 
        export HTML_DIR=$GITHUB_WORKSPACE/src
        export DATA_DIR=$GITHUB_WORKSPACE/code/data
        export WWW_DIR=$GITHUB_WORKSPACE/www
        echo $WWW_DIR
        lua web.lua

    - name: Test if it works
      run: cat www/index.html



